Repository ce4951/networking, pull requests merged in 2018-10, with the labels that each got.

#8 Initial implementaion of channel monitor for STM32 board
  inc/ADC.h
  inc/Manchester_State.h
  inc/RCC.h
  inc/RTC.h
  inc/RX.h
  inc/date.h
  inc/gpio.h
  inc/interrupt_timer.h
  inc/keypad.h
  inc/lcd.h
  inc/piezo.h
  inc/ringbuffer.h
  inc/timer.h
  inc/uart_driver.h
  src/Manchester_State.c
  src/RX.c
  src/gpio.c
  src/interrupt_timer.c
  src/main.c
  src/syscalls.c
  src/uart_driver.c
  startup/startup_stm32.s
  startup/sysmem.c
Labels: ready for review and merge, tests passed

#9 Have a working channel monitor and transmitter
  inc/Transmitter.h
  inc/ringbuffer.h
  inc/uart_driver.h
  src/Manchester_State.c
  src/RX.c
  src/Transmitter.c
  src/interrupt_timer.c
  src/main.c
  src/ringbuffer.c
  src/uart_driver.c
Labels: ready for review and merge, tests passed

#10 Start Implementing Receiver and Switch to PC6 for RX
  inc/RX.h
  inc/receiver.h
  src/Manchester_State.c
  src/RX.c
  src/Transmitter.c
  src/main.c
  src/receiver.c
Labels: tests passed

#11 Add Receiving capabilities
  inc/Manchester_State.h
  inc/Transmitter.h
  inc/receiver.h
  src/Manchester_State.c
  src/RX.c
  src/Transmitter.c
  src/main.c
  src/receiver.c
Labels: ready for review and merge, tests passed

#12 Add CRC functionality
  inc/crc.h
  src/crc.c
  src/main.c
Labels: ready for review and merge, tests passed

#14 Fix CRC to only CRC message field
  inc/crc.h
  src/crc.c
  startup/startup_stm32.s
Labels: ready for review and merge
